<?php

namespace ExchangeRateBundle\Repository;

/**
 * ExchangeRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExchangeRateRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get the latest currency rates.
     *
     * @return array
     */
    public function getLatestCurrencyRates()
    {
        $sql = 'SELECT r.symbol, r.amount, r.provider, r.createdAt FROM ExchangeRateBundle:ExchangeRate r WHERE r.id IN (SELECT MAX(r1.id) FROM ExchangeRateBundle:ExchangeRate r1 GROUP BY r1.symbol)';
        return $this->getEntityManager()
            ->createQuery($sql)
            ->getResult();
    }
}
